import "dotenv/config";
import cors from "cors";
import express from "express";
import morgan from "morgan";

const app = express();
const port = process.env.PORT || 7000;
const controlKey = process.env.INCIDENTIQ_CONTROL_KEY || "incidentiq-local-control";
const severityMultiplier = { low: 1, medium: 1.7, high: 2.6, critical: 4 };
let anomaly = null;

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

const wait = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
const currentAnomaly = () => {
  if (anomaly && Date.now() >= anomaly.expiresAt) anomaly = null;
  return anomaly;
};

app.use(async (req, res, next) => {
  if (req.path.startsWith("/__incidentiq")) return next();
  const active = currentAnomaly();
  if (!active) return next();

  const factor = severityMultiplier[active.severity] || 1;
  if (active.type === "SERVICE_DOWN") {
    return res.status(503).json({ message: "Test API unavailable due to controlled IncidentIQ anomaly" });
  }
  if (active.type === "ERROR_RATE_INCREASE" && Math.random() < Math.min(0.2 * factor, 0.9)) {
    return res.status(500).json({ message: "Controlled test failure generated by IncidentIQ" });
  }

  const delays = {
    LATENCY_SPIKE: 250,
    MEMORY_LEAK_SIMULATION: Math.min(200 + (Date.now() - active.startedAt) / 20, 2500),
    DATABASE_SLOWDOWN: 180,
  };
  if (delays[active.type]) await wait(delays[active.type] * factor);
  next();
});

app.get("/health", (req, res) => res.json({ status: "healthy", service: "IncidentIQ Test API", anomaly: currentAnomaly()?.type || null }));
app.get("/api/products", (req, res) => res.json({
  products: [
    { id: 1, name: "Monitor", price: 299 },
    { id: 2, name: "Keyboard", price: 89 },
    { id: 3, name: "Headset", price: 129 },
  ],
  timestamp: new Date(),
}));

app.post("/__incidentiq/anomalies", (req, res) => {
  if (req.get("x-incidentiq-control-key") !== controlKey) return res.status(401).json({ message: "Invalid IncidentIQ control key" });
  const { type, severity, duration } = req.body;
  anomaly = { type, severity, duration, startedAt: Date.now(), expiresAt: Date.now() + Number(duration) * 1000 };
  res.status(201).json({ message: "Controlled anomaly enabled", anomaly });
});

app.delete("/__incidentiq/anomalies", (req, res) => {
  if (req.get("x-incidentiq-control-key") !== controlKey) return res.status(401).json({ message: "Invalid IncidentIQ control key" });
  anomaly = null;
  res.json({ message: "Controlled anomaly cleared" });
});

app.get("/__incidentiq/status", (req, res) => {
  if (req.get("x-incidentiq-control-key") !== controlKey) return res.status(401).json({ message: "Invalid IncidentIQ control key" });
  res.json({ anomaly: currentAnomaly() });
});

app.listen(port, () => console.log(`IncidentIQ Test API running on http://localhost:${port}`));
